KEY_WORD("Kono, Giorno Giovanna, niwa yume ga aru", 39, "main",          FUNC,       1, MAIN,   "file '../sound/kono_jorno.ts'\n"    )
KEY_WORD("Kira Kuin baitsa dasuto",                 23, "return",        OPERATION,  2, RETURN, "file '../sound/kira.ts'\n"          )
KEY_WORD("Yare Yare Daze",                          14, ";",             LR,         3, LR,     "file '../sound/Yare_Yare_Daze.ts'\n")
KEY_WORD("Arrivederci",                             11, "print",         FUNC,      10, PRINT,  "file '../sound/Arrivederci.ts'\n"   ) 
KEY_WORD("Kono",                                     4, "scan",          FUNC,      11, SCAN,   "file '../sound/Kono_Dio_da.ts'\n"   )
KEY_WORD("Mousukoshite ora ora desuka",             27, "if",            OPERATION, 30, IF,     "file '../sound/Darby.ts'\n"         ) 
KEY_WORD("Gorudo Ekusuperiensu Rekuiemu",           29, "while",         OPERATION, 31, WHILE,  "file '../sound/Requiem.ts'\n"       )  
KEY_WORD("Awaken",                                   6, "=",             OPERATION, 32, ASSIGN, "file '../sound/Awaken.ts'\n"        )
KEY_WORD("Za Warudo! Toki wo Tomare!",              26, "{",             SEPARATOR, 20, LSB,    "file '../sound/Za_warudo.ts'\n"     )
KEY_WORD("ROAD ROLLER DA!",                         15, "}",             SEPARATOR, 21, RSB,    "file '../sound/Road_roller.ts'\n"   )
KEY_WORD("(",                                        1, "(",             SEPARATOR, 22, LB,     ""                                   )
KEY_WORD(")",                                        1, ")",             SEPARATOR, 23, RB,     ""                                   )
KEY_WORD(",",                                        1, ",",             SEPARATOR, 24, COMMA,  ""                                   )
KEY_WORD("ORAORAORAORA",                            12, "+",             OPERATION, 41, ADD,    "file '../sound/Ora.ts'\n"           )
KEY_WORD("ARIARIARIARI",                            12, "-",             OPERATION, 42, SUB,    "file '../sound/Ari.ts'\n"           )
KEY_WORD("MUDAMUDAMUDA",                            12, "*",             OPERATION, 43, MUL,    "file '../sound/muda.ts'\n"          )
KEY_WORD("HORAHORAHORA",                            12, "/",             OPERATION, 44, DIV,    "file '../sound/Hora.ts'\n"          )
KEY_WORD("DORARARARARA",                            12, "^",             OPERATION, 45, POW,    "file '../sound/Dora.ts'\n"          )
KEY_WORD("USHYAAAA",                                 8, ">",             OPERATION, 46, BAA,    ""                                   )
KEY_WORD("URYAAAAA",                                 8, "<",             OPERATION, 47, BAB,    ""                                   )
KEY_WORD("NIIIIICE",                                 8, "==",            OPERATION, 48, BAE,    ""                                   )
KEY_WORD("UBASHAAA",                                 8, ">=",            OPERATION, 49, BAAE,   ""                                   ) 
KEY_WORD("UOSHAAAA",                                 8, "<=",            OPERATION, 50, BABE,   ""                                   )
KEY_WORD("WRYYYYYY",                                 8, "!=",            OPERATION, 51, BANE,   ""                                   ) 
KEY_WORD("Hamon",                                    5, "differentiate", OPERATION, 52, DIF,    "file '../sound/Hamon.ts'\n"         )       
KEY_WORD("Suta purachina",                          14, "ln",            FUNC,      65, LN,     ""                                   )
KEY_WORD("Haierofanto Gurin",                       17, "sin",           FUNC,      66, SIN,    ""                                   )
KEY_WORD("Desu Satin",                              10, "cos",           FUNC,      67, COS,    ""                                   )
KEY_WORD("Atumu-shin",                              10, "tg",            FUNC,      68, TG,     ""                                   )
KEY_WORD("Kurimu",                                   6, "ctg",           FUNC,      69, CTG,    ""                                   )
KEY_WORD("Jasutisu",                                 8, "arcsin",        FUNC,      70, ARCSIN, ""                                   )
KEY_WORD("Mudi Burusu",                             11, "arccos",        FUNC,      71, ARCCOS, ""                                   )
KEY_WORD("Sutikkyi Fingazu",                        16, "arctg",         FUNC,      72, ARCTG,  ""                                   )
KEY_WORD("Kingu Kurimuzon",                         15, "arcctg",        FUNC,      73, ARCCTG, ""                                   )
KEY_WORD("Shiruba Chariottsu",                      18, "sh",            FUNC,      74, SH,     ""                                   )
KEY_WORD("Kureiji Daiyamondo",                      18, "ch",            FUNC,      75, CH,     ""                                   )
KEY_WORD("Kira Kuin",                                9, "th",            FUNC,      76, TH,     ""                                   ) 
KEY_WORD("Ekozu",                                    5, "cth",           FUNC,      77, CTH,    ""                                   )
KEY_WORD("Hebunzu Doa",                             11, "sqrt",          FUNC,      78, SQRT,   ""                                   )
KEY_WORD("Sekkusu Pisutoruzu",                      18, "exp",           FUNC,      79, EXP,    ""                                   )