KEY_WORD("この, Giorno Giovanno, にわ ゆめ が ある", 49, "main",         FUNC,       1,  MAIN,   "file '../sound/kono_jorno.ts'\n"    )
KEY_WORD("キラー・クイーン バイツァ・ダスト",           49, "return",      OPERATION,   2, RETURN, "file '../sound/kira.ts'\n"          )
KEY_WORD("やれやれだぜ",                            18, ";",            LR,         3,  LR,     "file '../sound/Yare_Yare_Daze.ts'\n")
KEY_WORD("アリーヴェデルチ",                         24, "print",        FUNC,      10,  PRINT,  "file '../sound/Arrivederci.ts'\n"   )
KEY_WORD("この",                                    6, "scan",         FUNC,      11, SCAN,   "file '../sound/Kono_Dio_da.ts'\n"   )
KEY_WORD("もしかしてオラオラですかあ",                 39, "if",           OPERATION, 30, IF,     "file '../sound/Darby.ts'\n"         ) 
KEY_WORD("むげん つくよみ",                          22, "while",        OPERATION, 31, WHILE,  "file '../sound/Requiem.ts'\n"       )
KEY_WORD("アウェイクン",                            18, "=",             OPERATION, 32, ASSIGN, "file '../sound/Awaken.ts'\n"        )
KEY_WORD("Za Warudo! Toki wo Tomare!",            26, "{",             SEPARATOR, 20, LSB,    "file '../sound/Za_warudo.ts'\n"     )
KEY_WORD("ROAD ROLLER DA!",                       15, "}",             SEPARATOR, 21, RSB,    "file '../sound/Road_roller.ts'\n"   )
KEY_WORD("(",                                      1, "(",             SEPARATOR, 22, LB,     ""                                   )
KEY_WORD(")",                                      1, ")",             SEPARATOR, 23, RB,     ""                                   )
KEY_WORD(",",                                      1, ",",             SEPARATOR, 24, COMMA,  ""                                   )
KEY_WORD("ORAORAORAORA",                          12, "+",             OPERATION, 41, ADD,    "file '../sound/Ora.ts'\n"           )
KEY_WORD("ARIARIARIARI",                          12, "-",             OPERATION, 42, SUB,    "file '../sound/Ari.ts'\n"           )
KEY_WORD("MUDAMUDAMUDA",                          12, "*",             OPERATION, 43, MUL,    "file '../sound/muda.ts'\n"          )
KEY_WORD("HORAHORAHORA",                          12, "/",             OPERATION, 44, DIV,    "file '../sound/Hora.ts'\n"          )
KEY_WORD("DORARARARARA",                          12, "^",             OPERATION, 45, POW,    "file '../sound/Dora.ts'\n"          )
KEY_WORD("USHYAAAA",                               8, ">",             OPERATION, 46, BAA,    ""                                   )
KEY_WORD("URYAAAAA",                               8, "<",             OPERATION, 47, BAB,    ""                                   )
KEY_WORD("NIIIIICE",                               8, "==",            OPERATION, 48, BAE,    ""                                   )
KEY_WORD("UBASHAAA",                               8, ">=",            OPERATION, 49, BAAE,   ""                                   ) 
KEY_WORD("UOSHAAAA",                               8, "<=",            OPERATION, 50, BABE,   ""                                   )
KEY_WORD("WRYYYYYY",                               8, "!=",            OPERATION, 51, BANE,   ""                                   )
KEY_WORD("波紋",                                   6, "differentiate", OPERATION, 52,  DIF,    "file '../sound/Hamon.ts'\n"         ) 
KEY_WORD("スタープラチナ",                          21, "ln",            FUNC,      65, LN,      ""                                  )
KEY_WORD("ハイエロファントグリーン",                  36, "sin",           FUNC,      66, SIN,    ""                                   )
KEY_WORD("デスサーティーン",                        24, "cos",           FUNC,       67, COS,    ""                                   )
KEY_WORD("アトゥム神",                             15, "tg",            FUNC,       68, TG,     ""                                   )
KEY_WORD("クリーム",                               12, "ctg",           FUNC,      69, CTG,     ""                                   )
KEY_WORD("ジャスティス",                            18, "arcsin",        FUNC,      70, ARCSIN,  ""                                  )
KEY_WORD("ムーディー・ブルース",                     30, "arccos",        FUNC,      71, ARCCOS,  ""                                  )
KEY_WORD("スティッキィ・フィンガーズ",                39, "arctg",         FUNC,      72, ARCTG,   ""                                  )
KEY_WORD("キング・クリムゾン",                       27, "arcctg",        FUNC,      73, ARCCTG,  ""                                  )
KEY_WORD("シルバーチャリオッツ",                     30, "sh",            FUNC,      74, SH,      ""                                  )
KEY_WORD("クレイジー・ダイヤモンド",                  36, "ch",            FUNC,      75, CH,      ""                                  )
KEY_WORD("キラークイーン",                          21, "th",            FUNC,      76, TH,      ""                                   ) 
KEY_WORD("エコーズ",                               12, "cth",           FUNC,      77, CTH,     ""                                   )
KEY_WORD("ヘブンズ・ドアー",                        24, "sqrt",           FUNC,      78, SQRT,   ""                                   )
KEY_WORD("セックス・ピストルズ",                     30, "exp",           FUNC,       79, EXP,    ""                                  )